/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    BannerCarousel: typeof import('./src/components/common/BannerCarousel.vue')['default']
    BottomTabBar: typeof import('./src/components/common/BottomTabBar.vue')['default']
    CategoryTabs: typeof import('./src/components/common/CategoryTabs.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    FloatingButton: typeof import('./src/components/common/FloatingButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ModuleCard: typeof import('./src/components/common/ModuleCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/common/SearchBar.vue')['default']
    ToolItem: typeof import('./src/components/common/ToolItem.vue')['default']
  }
}
